name: Build image

on:
  push:

jobs:
  
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}