
name: Deploy to Cloud

on:
  workflow_call:
    inputs:
      tag:
        description: The tag to deploy
        required: true
        type: string
        default: 'latest'
    secrets:
      GCP_SERVICE_ACCOUNT:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AZURE_KUBECONFIG:
        required: true
      AZURE_CLUSTER_NAME:
        required: true
      CLOUDFLARE_TOKEN:
        required: true
      CLOUDFLARE_ZONE_ID:
        required: true
      


jobs:

  staging-gcp:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: http://staging.monacloud.xyz

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Print GCP service account
        run: |
          echo $GCP_SERVICE_ACCOUNT

      - name: Configure GCP credentials
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Get GKE credentials
        id: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: ${{ secrets.CLUSTER_NAME }}
          location: us-central1

      - name: Get new container image tag
        id: image-tag
        env:
          GIT_TAG_NAME: ${{ inputs.tag }}
        run: |
          echo "::set-output name=image::ghcr.io/$GITHUB_REPOSITORY:$GIT_TAG_NAME"
      
      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s.yaml
          images: |
            ${{ steps.image-tag.outputs.image }}
      
      - name: Get service ingress IP address
        run: |
            echo "SVC_INGRESS_IP=$(kubectl get svc monacloud-svc -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Update Cloudflare DNS records
        uses: rez0n/create-dns-record@v2.1
        with:
          type: "A"
          name: "staging.monacloud.xyz"
          content: ${{ env.SVC_INGRESS_IP }}
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}

  preview-aws:
    needs: staging-gcp
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: http://preview.monacloud.xyz

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set Kubeconfig
        env:
            CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        run: |
         aws eks --region us-east-1 update-kubeconfig --name "$CLUSTER_NAME" 

      - name: Get new container image tag
        id: image-tag
        env:
          GIT_TAG_NAME: ${{ inputs.tag }}
        run: |
          echo "::set-output name=image::ghcr.io/$GITHUB_REPOSITORY:$GIT_TAG_NAME"
      
      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s.yaml
          images: |
            ${{ steps.image-tag.outputs.image }}

      - name: Get service ingress hostname
        run: |
            echo "SVC_INGRESS_HOSTNAME=$(kubectl get svc monacloud-svc -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')" >> $GITHUB_ENV

      - name: Update Cloudflare DNS records
        uses: rez0n/create-dns-record@v2.1
        with:
          type: "CNAME"
          name: "preview.monacloud.xyz"
          content: ${{ env.SVC_INGRESS_HOSTNAME }}
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}

  production-azure:
    needs: preview-aws
    runs-on: ubuntu-latest
    environment:
      name: production
      url: http://monacloud.xyz
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Set context from Kubeconfig
        uses: azure/k8s-set-context@v1
        id: setcontext
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.AZURE_KUBECONFIG }} 
          context: ${{ secrets.AZURE_CLUSTER_NAME }}          

      - name: Get new container image tag
        id: image-tag
        env:
          GIT_TAG_NAME: ${{ inputs.tag }}
        run: |
          echo "::set-output name=image::ghcr.io/$GITHUB_REPOSITORY:$GIT_TAG_NAME"
      
      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s.yaml
          images: |
            ${{ steps.image-tag.outputs.image }}
            
      - name: Get service ingress IP address
        run: |
            echo "SVC_INGRESS_IP=$(kubectl get svc monacloud-svc -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Update Cloudflare DNS records
        uses: rez0n/create-dns-record@v2.1
        with:
          type: "A"
          name: "monacloud.xyz"
          content: ${{ env.SVC_INGRESS_IP }}
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}
